# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YBuVZhLEzTkU9pXK3C1IwGMLFxpcBi5a
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
from flask import Flask, request, render_template




app = Flask(__name__)




def set_params(IW, IF, VW, FP):

    model = keras.models.load_model(r"C:/UserC:/Users/acer/Desktop/model")
    prediction = model.predict([IW, IF, VW, FP])

    return prediction[0][0]





@app.route('/', methods=['post', 'get'])

def app_calculation():
    param_lst = []
    message = ''
    if request.method == 'POST':


        for i in range(1,13,1):
            param = request.form.get(f'param{i}')
            param_lst.append(float(param))

        message = set_params(*param_lst)

    return render_template("C:/UserC:/Users/acer/Desktop/index.html", message = message)


app.run(debug=True)